// This file was autogenerated by calcdeps.py
goog.addDependency("../../../control.js", ['mvc.Control'], ['goog.dom', 'goog.object', 'goog.ui.Component']);
goog.addDependency("../../../model.js", ['mvc.Model'], ['goog.array', 'goog.dom', 'goog.events', 'goog.events.EventTarget', 'goog.object']);
goog.addDependency("../../../model_test.js", [], ['mvc.Model', 'goog.testing.jsunit']);
goog.addDependency("../../../test_deps.js", [], []);
