// This file was autogenerated by calcdeps.py
goog.addDependency("../../../collection.js", ['mvc.Collection'], ['goog.events.EventTarget']);
goog.addDependency("../../../collection_test.js", [], ['mvc.Collection', 'mvc.Model', 'goog.testing.PropertyReplacer', 'goog.testing.jsunit']);
goog.addDependency("../../../control.js", ['mvc.Control'], ['goog.dom', 'goog.object', 'goog.ui.Component']);
goog.addDependency("../../../control_test.js", [], []);
goog.addDependency("../../../model.js", ['mvc.Model'], ['goog.array', 'goog.dom', 'goog.events', 'goog.events.EventTarget', 'goog.object']);
goog.addDependency("../../../model_test.js", [], ['mvc.Model', 'goog.testing.jsunit']);
goog.addDependency("../../../router.js", ['mvc.Router'], ['goog.events', 'goog.history']);
goog.addDependency("../../../test_deps.js", [], []);
goog.addDependency("../../../sync/ajax.js", ['mvc.sync.Ajax'], ['mvc.sync', 'goog.net.XhrIo']);
goog.addDependency("../../../sync/sync.js", ['mvc.sync'], []);
goog.addDependency("../../../testApp/testApp.js", [], []);
